baseURL       = "https://denzuko.github.io/stream-assets/"
locale        = "en-us"
title         = "stream-assets"
disableKinds  = ["home","section","taxonomy","term","RSS","sitemap","robotsTXT"]

[outputs]
  page = ["HTML"]
