baseURL       = "https://stream-assets.dwightaspencer.com/"
locale        = "en-us"
title         = "stream-assets"
disableKinds  = ["section","taxonomy","term","RSS","sitemap","robotsTXT"]

[outputs]
  home = ["HTML"]
  page = ["HTML"]

[minify]
  minifyOutput = false
